services:
  pdv-app:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .:/app
    depends_on:
      pdv-db:
        condition: service_healthy

    command:
      - bash
      - -c
      - >
        mvn package -DskipTests &&
        java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005 -jar target/pdv-0.0.1-SNAPSHOT.war
    
  pdv-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: pdv
    ports:
      - "3306:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    